### ISSUE TITLE
JavaFX for x64-Firefox not available for launching webstart

### ISSUE THREAD

**Issue by Benko111** [Rohitjoshi9023/Brutal-wordlist-Generator#1]
I'm surprised how fast this is. Quit good actually. Any idea how I could get the webstart running with new Quantum Firefox?

**Comment by Benko111** [comment]
More importantly, whats's the codepage of the output? Neither ANSI nor UTF-8, my file list looks binary.

**Comment by Rohitjoshi9023** [comment]
Sorry to say But Code is Confidential and to Run on Web-browser you can check the reference link given below.
[](https://docs.oracle.com/javafx/2/get_started/basic_deployment.htm)

**Comment by Rohitjoshi9023** [comment]
Sorry to say But Code is Confidential and to Run on Web-browser you can check the reference link given below.
[LINK](https://docs.oracle.com/javafx/2/get_started/basic_deployment.htm)

**Comment by Rohitjoshi9023** [comment]
Sorry to say But Code is Confidential and to Run on Web-browser you can check the reference link given below.
https://docs.oracle.com/javafx/2/get_started/basic_deployment.htm
